<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>13.0</LangVersion>

    <!-- Versioning rules: 1.0.0.0 -->
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>

    <!-- Application Metadata -->
    <Title>WoodStream Audio Editor</Title>
    <Product>WoodStream Audio Editor</Product>
    <Description>Podcast Audio Processor and Metadata Tagger</Description>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
    <Resource Include="Resources\app.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="NAudio" Version="3.1.0" />
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="VST.NET2-Host" Version="2.1.10" />
  </ItemGroup>

</Project>
